### ISSUE TITLE
not issue

### ISSUE THREAD

**Issue by raveit65** [kolanos/gnome-high-contrast-inverse-theme#1]
Hi,
I'm from mate-desktop and i wanna fork your GTK3 part to mate-themes.
We have different branches for every GTK3 version, so which GTK3 version do you support?
We have some users who will like and need your work ;)
Thank you

**Comment by db-src** [comment]
My issue would be this:

The HighContrastInverse theme is **not** dropped. GTK+ still generates it from the same SASS sources as the 'main' HighContrast. Therefore, it _is_ kept up to date - at least  since a recent flurry of fixes for some years-old bugs...

The actual problem appears to be that GNOME does not provide any accessible way to select it, instead requiring environment variables or suchlike.

It's a great theme, *and* still in active development (at least recently), but it seems that it's just been buried from view for some reason, with little or no way of getting to it from any GNOME GUI.

**Comment by raveit65** [comment]
Thanks for answering after 3 years.
All is done now :-)
